### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by dsmiley** [OpenSextant/SolrTextTagger#23]
Version 2.0-SNAPSHOT has been used quite a bit at MITRE and has had some enhanced tests -- it's solid.  The memory usage is better and it's more flexible to build/maintain indices since it's based directly off of Lucene instead of building a custom persisted memory structure, and it's simpler code too.  The tagging performance wasn't specifically measured, but it was in aggregate with the rest of OpenSextant and there was no marked difference -- that's success as far as I'm concerned.

What 2.0 lacks as of this writing is v1.2's ability to use more rich text analysis, thanks to @westei.  See #20. I'm a little conflicted on wether to just release it.  I was about to announce that it'll happen anyway next week but I think this big feature mis-match and no truly pressing reason to release 2.0 quite yet so I should hold up, and document some remaining issues.

When 2.0 does get released, the master branch will be renamed to 1_x, and MemPF will become master.

**Comment by dsmiley** [comment]
I'm going to release 2.0 next week, moving into master branch position, and put the current master as a 1.x branch.  1.1 will remain a viable choice as it supports more flexible text analysis choices. I'll push 2.0 to Maven as well.

**Comment by mubaldino** [comment]
thanks, Dave.  I published a 2.0-beta snapshot internally and have been using that copy to simplify things. java/SSL woes abound back here at the ranch.  Regards, marc

**Comment by dsmiley** [comment]
I created a "v1x" branch off master, then deleted master.  Then I renamed MemPF to master.  You *may* have issues with your existing checkout, and this will explain it but it should be fixable.  I'll push 2.0 in the morning.

**Comment by dsmiley** [comment]
I released 2.0.  It should sync to Maven Central within 2 hours, if I recall.
