### ISSUE TITLE
Next best postingsFormat for fieldType

### ISSUE THREAD

**Issue by sujitpal** [OpenSextant/SolrTextTagger#38]
This is more of a question than an issue, and not terribly urgent, but would help if you could answer...

I noticed that a default Solr 5 instance (-Xmx 512m) ran out of memory after about ingesting 10 million terms in the FST. I have since increased the -Xmx to 6GB so I have some breathing room (~ 120 million terms by extrapolation), but I was wondering if you could recommend a postingsFormat for the tag fieldType that can spill over into disk (or can work entirely from disk in the worst case). The boxes have SSDs so the disk penalty is not as great as with spinning disks.

I see that the possible values for postingsFormat (according to Dmitry Kan's comment on a page in the Solr ref guide) are - Lucene40, Lucene41, Pulsing41, SimpleText, Memory, BloomFilter, Direct, FSTPulsing41, FSTOrdPulsing41, FST41, and FSTOrd41. Going by the name I thought BloomFilter may be a good choice but Solr gives a runtime error. I tried removing the postingsFormat attribute and it works but I was wondering if there was some setting that is preferable after "Memory".

Also my understanding is that I would have to reindex all the content if I changed the postingsFormat, is that correct?

Thanks in advance for your answers.

**Comment by dsmiley** [comment]
Glad to hear from you again Sujit :-)

This is a great question.  First, know that most (all?) of these postings formats will consume the most amount of memory during indexing, particularly when Lucene segments merge.  Telling Lucene/Solr to "optimize" (i.e. merge all segments) will be peek memory, particularly if searching is concurrent during this.  Your solution right now could simply be not to "optimize" assuming you are optimizing -- or at least optimize to no less than X segments (a few?) via "&optimize=true&maxSegments=4"

"Memory" puts all index/lookup data associated with the field it is applied to into memory into FSTs + more.  For very small data sets, "Direct" uses no fancy FST compact data structures and so will use a lot more space but will be even faster.  To use _less_ memory, I think the most important/valuable thing to keep in memory is the "term dictionary", which is traversed a ton in tagging.  Memory, and all the posting formats that start with "FST" put the term dictionary in memory.  The tagger does not require/use term ordinals ("Ord" in the format name), so no need to use a postings format with that.  Thus, I think "FST41" is the next best choice.  FSTPulsing41 should be faster than FST41 since names with a single document have that doc ID tacked onto the term dictionary (this is called pulsing) but I suspect that one will use a similar amount of heap memory (& speed) to "Memory" for tagging applications since most name tokens have exactly 1 document to point to.  Should you decide to do some benchmarking, it's worth trying it still.

**Comment by dsmiley** [comment]
You'd definitely need to re-index if you change the postings format.

**Comment by sujitpal** [comment]
Thanks David, nice talking again, and thanks a lot for the information. I thought about it, and decided that I'd stay with the Memory setting. The contents of our index are lexicons, and we use the /tag service as one of the services (there is also fuzzy matching which needs the input document to be broken up into phrases and preprocessed). Our index size is currently 26.3 million entries and currently consumes 1.4GB heap out of the (now) available 6 GB. So there is lots of room to grow, and we can also go bigger on the RAM if needed at some point. Also since we need to annotate against one dictionary at a time, we could also scale out horizontally in case thats cheaper/possible (as long as all individual lexicons fits into the Solr JVM).

**Comment by sujitpal** [comment]
Closing issue, thanks again for all your help.

**Comment by dsmiley** [comment]
CC @mubaldino @westei 
The Lucene "Memory" postings format will likely be going away, at least if it cannot be demonstrated to be superior to the alternatives.  The proposal for its removal is here https://issues.apache.org/jira/browse/LUCENE-8267 of which there is some obvious tension/contention around removing stuff.  I'm hoping @sujitpal or @mubaldino  or @westei in your respective projects could do a quick(?) experiment to compare it to the next best thing which is `postingsFormat="FST50"`
Hopefully it'll perform nearly as well and the MemoryPostingsFormat can be dropped, but maybe it won't?

**Comment by dsmiley** [comment]
I examined FST50 closely and I suspect it will perform well for the tagger because a singleton-posting (i.e. an analyzed name that is _unique_) will be "pulsed" (included) directly into the FST.  This ought to be the common case for the data/use-case of OpenSextant geotagging.  I'm not sure if this is common or not for other uses.

**Comment by mubaldino** [comment]
If this is transparent solution to SolrTextTagger users, I'll consider testing out a snapshot patch for Solr 6.6 (s-t-t v2.4.1?), if indeed that is possible.   I see this involves a schema change on my end -- so to really push the envelope and test a potential real OOM issue I'd be rebuilding a good size gazetteer.  Anyway, data build and tests of this sort take hours in the background.  I'm game for testing if the procedure for testing and judging tests is reasonable ... procedural.   As far as weighing in on a postingsformat code change, ... if it is transparent to me, I don't really have an opinion.   Performance testing will help me choose.

marc

**Comment by dsmiley** [comment]
This is about speed not memory use; so don't worry about the OOM.  The Java memory/heap needs of `FST50` will be <= that of `Memory`.  Yes it's simply a schema change in Solr (with re-index) to switch.

**Comment by sujitpal** [comment]
Hi David,

Thanks for bringing this to our attention and sorry for the delay in
responding.

Just to let you know my current setup is solr 5.0.0 and SolrTextTagger
pulled from Github around that time frame, with postingsFormat="Memory". I
can run a test with latest Solr 7.3.0 with a medium sized dictionary (3M
entries) with both postingsFormat (Memory and FST50) and get back with
results. I will try to get back to this group optimistically end of this
week, or middle of next week latest.

-sujit

**Comment by sujitpal** [comment]
I built a SolrTextTagger index (dictionary?) using the cities1000.txt file, then ran 100 documents through it, configuring postingsFormat=Memory the first time and FST50 the second time. FST50 seems slower overall and has more variance in response time (QTime) as shown in the boxplots below:

![image](https://user-images.githubusercontent.com/1972473/39461152-a7e00fb0-4cbd-11e8-8fa2-eae3f8c48d4c.png)

or as shown by the histograms below:

![image](https://user-images.githubusercontent.com/1972473/39461185-c91bf5cc-4cbd-11e8-9275-3367b4dc3b2b.png)

A very crude check (comparing the total number of annotations per document between the two runs) show that both postingFormat settings give the same results, which I guess is expected but I wanted to make sure anyway.

One small caveat - my use case is slightly different from the base SolrTextTagger use case, so I had to modify the recipe with in the QUICK_START.md a bit (will update details on the SoDA site), but the same modifications were applied in case of both postingFormat settings.

**Comment by dsmiley** [comment]
Thanks for investing time into doing this comparison @sujitpal !  

Curious; what are the sporadic small circles above the box plot?  Are those individual readings that are outliers?  If so then shouldn't the maximum reading of the box plot coincide with the top outlier?

Do you refer to SolrTextTagger's QUICK_START.md and does this imply your test was actually GeoNames data?

The reduction of qtime seems inside of 10% and so I think it's not a big deal to not have the MemoryPostingsFormat available for us for the SolrTextTagger.  At least not with your data and dictionary.  And there were surely memory gains even if that wasn't quantified here.

**Comment by sujitpal** [comment]
Yes, the circles represent outliers, the whiskers occur at the inter-quartile range (IQR) bounds, its median +/- 1.5 * (third quartile - first quartile), these are defined as outliers because they go beyond the IQR bounds. 

My dictionary for this experiment was built from the cities1000.txt file but the documents were the 100 from our [OA-STM-Corpus](https://github.com/elsevierlabs/OA-STM-Corpus) - the ones under SimpleText/SimpleText\_auto. I started with an internal dictionary (approximately 10x the size) but it was taking too long to reload each time I did something wrong, so I went with this one. I figured that since I was computing the diff, it didn't matter. I *will* be re-running the experiment using the internal dictionary, if you like I can let you know the results of that, although I doubt if it will be very different.

And I agree, while FST50 seems generally slower, the speed difference is quite negligible, and has advantages in that we are no longer RAM bound.

**Comment by dsmiley** [comment]
bq.  if you like I can let you know the results of that, although I doubt if it will be very different.

Nah; this is good enough; thanks.  

Unless someone else wants to jump in here and say they plan to do a quick test as well, I'm inclined to tell the other Lucene devs that MemoryPostingsFormat can go.

**Comment by mubaldino** [comment]
This seems fine to me. I've seen your analysis.  I likely won't get around to testing this until I migrate to Solr/Lucene 7.x.  
Thanks!
Marc

**Comment by dsmiley** [comment]
In 0e5d89291e4bc160b3431995a830c3f08dda270b I updated all references from "Memory" to "FST50"
