### ISSUE TITLE
Possible bug in merging default initArgs for Tagger request handler with request params

### ISSUE THREAD

**Issue by simonatdrg** [OpenSextant/SolrTextTagger#39]
I noticed that our consultant who was working on ou deployment of the tagger made the following change to TaggerRequesthandler.java  

***************
*** 354,360 ****
        return;//short circuit; nothing to do
      SolrParams topInvariants = new MapSolrParams(map);
      // By putting putting the top level into the 1st arg, it overrides request params in 2nd arg.
!     req.setParams(SolrParams.wrapDefaults(topInvariants, req.getParams()));
    }

--- 354,362 ----
        return;//short circuit; nothing to do
      SolrParams topInvariants = new MapSolrParams(map);
      // By putting putting the top level into the 1st arg, it overrides request params in 2nd arg.
**! // Fixed, this was merging in the wrong direction, Francois Schiettecatte
! //     req.setParams(SolrParams.wrapDefaults(topInvariants, req.getParams()));
!     req.setParams(SolrParams.wrapDefaults(req.getParams(), topInvariants));**
    }
  As far as I can see, it's a legitimate bug and fix, not corrected in current master (our source shapshot was from a year ago)

cheers

-Simon

**Comment by dsmiley** [comment]
According to the comment (to include the javadocs for the method):

    // By putting putting the top level into the 1st arg, it overrides request params in 2nd arg.

This is correct.  The "topInvariants" params are effectively made *invariants* (not overridable by the request).  Regardless, depending on those top level specified parameters is something I considered deprecated configuration that should be removed in lieu of doing things the normal Solr way of using defaults/appends/invariants as seen with other request handlers.
