### ISSUE TITLE
solr 5.2

### ISSUE THREAD

**Issue by hossmaa** [OpenSextant/SolrTextTagger#40]
Hi David

Thanks for the good work with SolrTextTagger.
Just wanted to say there seems to be a problem when updating to Solr 5.2.
Below is a snippet of the problem.

Cheers
A.

```
java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum;
	at org.opensextant.solrtexttagger.Tagger.process(Tagger.java:160)
	at org.opensextant.solrtexttagger.TaggerRequestHandler.handleRequestBody(TaggerRequestHandler.java:223)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
```

**Comment by dsmiley** [comment]
I'm glad you like it.
So annoyingly in Solr 5.2, this method referred to in your stack trace was changed without regard to backward-compatibility.  I vaguely recall at the time; I should have spoken up when I remember seeing that in Lucene.  Any way, I'm going to release the tagger 2.1 for Solr 5.0 & 5.1 support; and I'm then going to make 2.2-SNAPSHOT for 5.2.1 and forward.  It's a trivial change to the iterator() method; simply drop the argument to take no argument.
