### ISSUE TITLE
Change History, etc

### ISSUE THREAD

**Issue by mubaldino** [OpenSextant/SolrTextTagger#41]
David, 

greetings.  Hope all is well with you.

Could you please summarize any functional changes in going to 2.1?
I see Solr 5.2+ is about where Solr rev sits along with Java 7+.

Really basic change history and integration requirements (versions) would help the README or a second file on change/integration.

I'd like to start looking at Solr 5.3 in Xponents taggers (and so SolrTT 2.1)

thanks,
Marc

**Comment by dsmiley** [comment]
Hi Marc; I'm doing very well. It'd be nice to catch up some time.
Yes; I should absolutely maintain a CHANGES.txt!  I'll work on that and provide something soon-ish. I've got a conference to prepare for and it's getting to crunch time so I'll set a reminder to do this Monday the 19th.

**Comment by dsmiley** [comment]
Please see the new CHANGES.md.  Note that the current master branch, to become version 2.2, works only with Solr 5.2.x.  Supporting 5.3 would be yet another version unfortunately.  It's annoying to see some Lucene devs making such incompatible breaks to the API.  How about I release 2.2 now, then move on to updating master to support Solr 5.3?
