### ISSUE TITLE
Video of talk of system using SolrTextTagger at Spark Summit EU 2015

### ISSUE THREAD

**Issue by sujitpal** [OpenSextant/SolrTextTagger#42]
Thought you might want to know of this URL. This is my talk at Spark Summit EU 2015 where I describe a system that uses SolrTextTagger for exact case-sensitive and insensitive matching of dictionary entities in text to do NER.

Video: https://www.youtube.com/watch?v=gOe0aYAS8Do
Slides: http://www.slideshare.net/sujitpal/sseu-2015soda

Thanks,

**Comment by dsmiley** [comment]
Awesome Sujit!  I added a reference to the README.md.  I'll have to go watch this at my next lunch.

**Comment by dsmiley** [comment]
BTW in your talk you mentioned going to use straight Lucene to get more performance.  I think it's much easier to use EmbeddedSolrServer since you're already suing Solr.  This is what we've done within MITRE for using the text tagger.  In the tests there should be an example.

**Comment by sujitpal** [comment]
Thanks David! Hadn't considered doing this, but I think its a good idea (less change, and a chance to look at EmbeddedSolrServer), will check this out.
