### ISSUE TITLE
TermPrefixCursor incompatible with 5.3.0

### ISSUE THREAD

**Issue by joekiller** [OpenSextant/SolrTextTagger#43]
In Solr (Lucene) 5.3.0 the way that deleted docs are detected changed. The issue is https://issues.apache.org/jira/browse/LUCENE-6553 and their comment was "The postings, spans and scorer APIs no longer take an acceptDocs parameter. Live docs are now always checked on top of these APIs.".

So in `TermPrefixCursor.java` the following call no longer uses the liveDocs. This causes a few tests to fail.
```java
postingsEnum = termsEnum.postings(liveDocs, postingsEnum, PostingsEnum.NONE);
```
https://github.com/OpenSextant/SolrTextTagger/blob/b5f634faef2cc9464b1e808cb2460d5935a3b68b/src/main/java/org/opensextant/solrtexttagger/TermPrefixCursor.java#L116

Any advice on how to implement LUCENE-6553 within SolrTextTagger?

**Comment by joekiller** [comment]
PS there is one other deprecated call preventing 5.3.0 compatibility which I fixed here:

https://github.com/o19s/SolrTextTagger/tree/531-update

**Comment by dsmiley** [comment]
Hi Joe.
The liveDocs can be considered in postingsEnumToIntsRef in the loop that consumes postingsEnum.
I should probably release 2.2 (the current master) as it supports Lucene 5.2 and won't support 5.3.  These little changes are so annoying; back-compat used to be taken more seriously in Lucene.

**Comment by joekiller** [comment]
Thanks I updated the loop to use the liveDocs similar to how the patch did it in the tests.
