### ISSUE TITLE
Solr 5.3 Refactor Breaks testTagStreaming

### ISSUE THREAD

**Issue by joekiller** [OpenSextant/SolrTextTagger#44]
In the test [testTagStreaming](https://github.com/OpenSextant/SolrTextTagger/blob/master/src/test/java/org/opensextant/solrtexttagger/EmbeddedSolrNoSerializeTest.java#L108) the document response has changed due to [SOLR-7662](https://issues.apache.org/jira/browse/SOLR-7662). Per the comments in SOLR-7662, "javabin returns the primitive types of the fields while the text based writers return a IndexableField/StorableFIeld depends on whether you are in branch 5x or trunk". 

The change results in the field values being returned with the [following call](https://github.com/OpenSextant/SolrTextTagger/blob/master/src/test/java/org/opensextant/solrtexttagger/EmbeddedSolrNoSerializeTest.java#L129) as IndexableField/StorableField instead of the expected primitive value. 
```java
 assertEquals("Boston", refDoc.get().getFieldValue("name"));
```
How do you suggest adjusting for this?

I think this is the last bug for getting 5.3.1 working.

**Comment by dsmiley** [comment]
Looks like you fixed it.  The fix looks fine.  Can you please send one pull request with all these changes for 5.3.1?  Don't worry about bumping the version of the project in the POM.

**Comment by joekiller** [comment]
Cool. I don't like changing tests unless it's necessary. Seemed like the case this time. Thanks for the consult!
