### ISSUE TITLE
Solr 5.4 needs hppc updated

### ISSUE THREAD

**Issue by joekiller** [OpenSextant/SolrTextTagger#45]
hppc should be 0.7.1 for version 5.4 per https://issues.apache.org/jira/browse/SOLR-7791

**Comment by joekiller** [comment]
If I were to use this in 5.3.1 does the hppc library need to be the older
version since 5.3.1 had the older one?

**Comment by dsmiley** [comment]
I'm not certain but I strongly suspect it doesn't matter.
