### ISSUE TITLE
Solr 6.0 support

### ISSUE THREAD

**Issue by mubaldino** [OpenSextant/SolrTextTagger#50]
A first cut at compiling against Lucene 6.x showed the lowest level of APIs have changed, specifically in the Tagging Attribute implementation. 
org.apache.lucene.util.AttributeImpl has changed substantially, impacting org.opensextant.solrtexttagger.TaggingAttributeImpl

this was just a quick look at Solr 6.  Not urgent at all.

**Comment by westei** [comment]
HI I fixed this with #51

**Comment by dsmiley** [comment]
Once it's tested, I'll close.
