### ISSUE TITLE
Publish a Docker image of the text tagger.

### ISSUE THREAD

**Issue by dsmiley** [OpenSextant/SolrTextTagger#56]
It won't have data but it'll be Solr (from some other base image) with the tagger component added in.

The purpose is mostly to help people try this out.

**Comment by dsmiley** [comment]
@sujitpal did you mention that there is an image on docker hub already?  I can't find it -- Docker hub has bad search; they ought to use Solr ;-)

**Comment by sujitpal** [comment]
@dsmiley there is a docker image for SoDA which includes SolrTextTagger, this was contributed by @navd (who I noticed on the issues asking about fuzzy search) -- here is the [documentation about running SoDA on Docker](https://github.com/elsevierlabs-os/soda/blob/master/docs/docker-setup.md).

**Comment by dsmiley** [comment]
Thanks for the info.  I took a look (including reverse-engineering to get a Dockerfile) but it's gigabytes in size.  I prefer to carefully tune a Dockerfile for an ideal user experience.  Any way, if I get around to doing a SolrTextTagger Dockerfile, I'll start from the Solr base image.

**Comment by navd** [comment]
@dsmiley @sujitpal I have the dockerfile, which does the all installation at once. Maybe it makes more sense to use solr base image. Anyway, I will push the Dockerfile and comment the link here in a moment. Also, there is a possibility of reducing the size of existing image because I haven't cleaned up the downloaded tars after installation.

**Comment by dsmiley** [comment]
Now that Solr 7.4.0 contains the tagger, and Solr has it's own Docker image, there is very little need for a STT to have a dedicated docker image.  So I'll close this issue.  Of course if someone wants to take this up then they are welcome.
