### ISSUE TITLE
Release SolrTextTagger compatible with Apache Solr 6.3.0 

### ISSUE THREAD

**Issue by infodroids** [OpenSextant/SolrTextTagger#65]
Any plans to release SolrTextTagger version depending on Apache Solr 6.3.0, any time soon? (Its a question so should go to forum, but didn't find anything of that sort)

**Comment by dsmiley** [comment]
Hi; yes soon indeed.  There's going to be a Solr 6.4 release candidate this weekend, and so once 6.4 is official we'll release the text tagger which is expected to be compatible with both.  Note 6.3.0 was only recently supported -- #60

**Comment by infodroids** [comment]
Awesome, will keep and eye!
Thanks,

**Comment by dsmiley** [comment]
I just finished the release: https://repo1.maven.org/maven2/org/opensextant/solr-text-tagger/2.4/

**Comment by infodroids** [comment]
Wonderful! Thanks :+1:
