### ISSUE TITLE
implementing fuzzy matching

### ISSUE THREAD

**Issue by navd** [OpenSextant/SolrTextTagger#70]
Hi @dsmiley, I am using SolrTextTagger with SODA and trying to implement fuzzy matching for this. Earlier, you said you had some idea about implementing it. Can you provide me some guidance regarding the same, I feel bit lost.

Thanks,
Navdeep

**Comment by dsmiley** [comment]
Hi,
Can you provide me a URL of my response; my memory is hazy :-)
I think fuzzy matching is possible but probably very hard.  At least the most likely solution in my head would be Lucene's NRT Document Suggester which can do fuzzy matches, among other things.  It's internally based on an FST too, so it has the memory characteristics we want.  But that amounts to a rewrite of the guts of the tagger, which is already complicated code that requires expert Lucene knowledge.  Such a change would definitely amount to a new major version number.  Sorry I can't offer much assistance on exactly how to do this.

**Comment by matthewgertner** [comment]
I wonder if https://docs.rs/fst-levenshtein/0.1.0/fst_levenshtein/struct.Levenshtein.html would be useful.
