### ISSUE TITLE
OpenSextant projects add your topics.

### ISSUE THREAD

**Issue by mubaldino** [OpenSextant/SolrTextTagger#72]
David, 

please categorize SolrTextTagger using the "Add Topics" feature on your project page.  This is a new GitHub feature that helps consumers find source code repos faster.

thanks,
Marc

**Comment by dsmiley** [comment]
I gave it a shot.  I think you have permissions to do this too?

**Comment by mubaldino** [comment]
we can iterate on topic tags as much as we want... I did not want to lead the witness here by suggesting the topics or doing it myself.  I wanted to see how you might categorize it.

my thoughts -- add more general tags so that you gain the broadest coverage possible, but with the combination of your tags you maintain some niche.
```
solr
nlp
java
## these in addition to the ones you already have I guess.
```
While those tags might be too general, I think the tags you chose are less obvious.    There are 5 total "solr-plugin" projects in GitHub, and 237 projects tagged as "solr".    When I tagged Xponents I looked around at the tag popularity and tried to see if my offering fit in with other stuff also tagged that way.

Ultimately if someone looks for "solr", "java", "nlp" or some combination thereof using these short and common tags, all relevant active OpenSextant modules should come up.  If you choose "solr-plugin"  -- right,  I would expect SolrTextTagger to appear but not Xponents or other stuff, for example.

I do have permissions to tag an OpenSextant repo...   Topic tags are powerful, but effective when we agree on them. ;). Consider adding some more general tags.

**Comment by dsmiley** [comment]
I don't agree on "java" as it's both too broad and also, GitHub already knows full well what language (broken down by percent!) each project is written in.   Otherwise add the others if you wish.

**Comment by mubaldino** [comment]
good feedback. thanks.

m
