### ISSUE TITLE
SOLR 7

### ISSUE THREAD

**Issue by julianperry1965** [OpenSextant/SolrTextTagger#73]
Hi - any plans to port to SOLR 7?
We have a project using TextTagger and would prefer to migrate to SOLR 7.1.
Thank you.

**Comment by dsmiley** [comment]
Hi. I'll push a release out this week; perhaps today.

**Comment by dsmiley** [comment]
I committed the changes and tests pass -- https://travis-ci.org/OpenSextant/SolrTextTagger
Would you like to take it for a whirl to vet it first?    Perhaps @mubaldino too?

I've pushed a docs change to recommend docValues=true on the 'id' field.

Note that it's possible you may notice a slight performance decrease induced to a new Lucene API limitation about how "docValues" data is accessed.  I hope it's slight any way.  Of course the whole thing may be faster as any large software will have various improvements.

**Comment by julianperry1965** [comment]
Great - thank you for responding so fast - will take a look at it in the next few days.

**Comment by squallsama** [comment]
Is there any plans to have new release jar in maven central ?

**Comment by dsmiley** [comment]
Literally any day now there will be a 7.3 RC, and I'll test to see if master branch is compatible.  If so I'll do a release then.  If not; we'll see -- depends on what's involved.  Thanks for prodding.

**Comment by premrajnarkhede** [comment]
Thank you for this work! Looking forward to 7.3 release
