### ISSUE TITLE
Retrieve tagged term

### ISSUE THREAD

**Issue by hoangphan1509** [OpenSextant/SolrTextTagger#74]
Hi @dsmiley, 

Is there any way that we can retrieve the tagged term? Let say we have term `New England` and the query is 'New', the result only return offset for `New` in the query, can we also get the term `New England`? Thank you for the great SOLR plugin!

**Comment by dsmiley** [comment]
Hi,
If the input (what you call the query?) is "New", why would it match an indexed tag "New England"?  Or perhaps you mean flipped around?  Regardless, the tagger can return whatever fields you want from the indexed tag documents.  If you want to returned the input matched text between the offsets, then add the parameter matchText=true

**Comment by hoangphan1509** [comment]
Sorry, It's my mistake when applying WhitespaceTokenizer to index document. Thank you for your quick answer.
