### ISSUE TITLE
Can't create a schema with ConcatenateFilterFactory

### ISSUE THREAD

**Issue by Endmaril** [OpenSextant/SolrTextTagger#80]
Hello,

First thanks for this great contribution.
I am trying to setup a solr server with the text tagger but I can't manage to create a collection using the ConcatenateFilterFactory without getting an exception.

I tried compiling the 2.4 version and using it with solr 6.6.2.
I copied the `solr-text-tagger-2.4.jar` to the `server/lib` directory of my freshly downloaded version of solr, started solr and tried to follow the steps of  the quick start guide. When trying to create the schema, I end up with a 
`java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.TokenFilterFactory`

I tried adding some of the Lucene's jars to the lib folder to get rid of that (even though it didn't seem to be the right thing to do) and ended up with 
`java.lang.ClassCastException: class org.apache.lucene.analysis.tr.ApostropheFilterFactory`
after adding lucene-core-6.6.2.jar and lucene-analyzers-common-6.6.2.jar to the server/lib directory.

I tried a similar process with a freshly downloaded solr 7.2.1  and text tagger 2.5 and got pretty similar results (`Plugin init failure for [schema.xml] analyzer/filter: class org.opensextant.solrtexttagger.ConcatenateFilterFactory\nclass org.opensextant.solrtexttagger.ConcatenateFilterFactory` instead of the `ClassCastExcepction` after adding the lucene dependencies).

I am probably missing something obvious but can't seem to find out what.
Do you have any idea that could help me a bit ?
Thanks

**Comment by dsmiley** [comment]
Hi,
See https://github.com/OpenSextant/SolrTextTagger/blob/master/QUICK_START.md
Note where it says "Install the Tagger", that it references `SOLR_DIST_DIR/server/solr/lib/` which is not quite what you did.  That lib dir may not be there so create it if need be.

**Comment by Endmaril** [comment]
Thanks for the quick response.
Everything works as expected when putting the jar at this location.
I misread the location in the first place (missed something obvious as i said).
Thanks for pointing out the thing I missed and sorry for this little mistake.
