### ISSUE TITLE
Each tag in the output is an array of names and values instead of an object

### ISSUE THREAD

**Issue by dkincaid** [OpenSextant/SolrTextTagger#83]
While working with the version of the tagger that is included in Solr 7.4.0 t

```
{
  "responseHeader":{
    "status":0,
    "QTime":2},
  "tagsCount":1,
  "tags":[[
      "startOffset",4,
      "endOffset",15,
      "ids",["A18692784"]]
  ]
}
```
I would think that making this an array of objects would be easier to parse:

```
{
  "responseHeader":{
    "status":0,
    "QTime":2},
  "tagsCount":1,
  "tags":[{
      "startOffset": 4,
      "endOffset": 15,
      "ids": ["A18692784"]}
  ]
}
```
is there are reason it is formatted the way it is right now?

**Comment by dsmiley** [comment]
See: https://builds.apache.org/job/Solr-reference-guide-master/javadoc/response-writers.html#json-nl   set `json.nl=map`  Perhaps the example in the ref guide ought to do this.  Feel free to suggest a GitHub PR to Apache Solr doing this if you have the time.

**Comment by dkincaid** [comment]
Thanks for responding and for the quick and easy answer!
