### ISSUE TITLE
how to use the ConcatenateFilterFactory with solr 7.6

### ISSUE THREAD

**Issue by SriniSampath** [OpenSextant/SolrTextTagger#87]
Hi experts,

I am using the solr 7.6 version and unable to use the org.opensextant.solrtexttagger.ConcatenateFilterFactory (as solr.ConcatenateFilterFactory ) in the config. I could only use "solr.ConcatenateGraphFilterFactory". 

can someone please help me how to access the ConcatenateFilterFactory? if can not, what is the difference it would cause if I use the ConcatenateGraphFilterFactory?

Thanks.

**Comment by dsmiley** [comment]
solr.ConcatenateGraphFilterFactory is a superior replacement to ConcatenateFilterFactory (without the "Graph").  The graph one handles more diverse text analysis possibilities (e.g. synonyms).  The latter older one only exists in this repository, not upstream.

FYI for some background https://issues.apache.org/jira/browse/LUCENE-8332

Perhaps on the README.md here I should more clearly indicate this particular difference?  I'm not sure this repo here has a future now that 95% of it went directly into Solr.
